version: '3'

services:
  node:
    image: node:16-alpine
    container_name: react-app
    tty: true
    volumes:
      - ./node:/usr/src/app:cached
    ports:
      - "3000:3000"
    working_dir: "/usr/src/app/react-app"
    command: sh -c "yarn start"
    stdin_open: true